### ISSUE TITLE
Too long news events descriptions

### ISSUE THREAD

**Issue by higuyscd32oof** [swf541/ColdWarIronCurtain#10]
While playing my game till 1952 i found some rather long news events description that get out of the designated "newspaper" , here's the events in questions i got screenshots of:

![image](https://user-images.githubusercontent.com/40366672/71216608-387a7680-22bb-11ea-8c4c-3656262ff5ee.png)
![image](https://user-images.githubusercontent.com/40366672/71216615-403a1b00-22bb-11ea-9104-0e89408aaa25.png)

**Comment by Harain** [comment]
news window has been change, and many news events texts adapted to fit
please report if you find more
