### ISSUE TITLE
De Gasperi typo

### ISSUE THREAD

**Issue by PanUmbe** [swf541/ColdWarIronCurtain#103]
in history/countries/ITA - Italy.txt "Alcide De Gaperi" should be replaced with "Alcide De Gasperi".

**Comment by leftwinglow** [comment]
Fixed

**Comment by PanUmbe** [comment]
It still wrong at line 265.

**Comment by leftwinglow** [comment]
> 
> 
> It still wrong at line 265.

Good catch, sorry about prematurely closing. Thanks for the report.

**Comment by PanUmbe** [comment]
Don't worry, I just remember the typo was present twice.

**Comment by PanUmbe** [comment]
I'm sorry to come back to this issue, but now at line 275 is mispelled as "Gapseri".
