### ISSUE TITLE
Cant copress the winrar cold war iron cutrian winrar foilder need help 

### ISSUE THREAD

**Issue by Vagstags** [swf541/ColdWarIronCurtain#109]

**Comment by christopher0936** [comment]
Apologies, but this is simply too incoherent for me to be able to give any detailed assistance with your problem. There is a troubleshooting guide available [HERE](https://docs.google.com/document/d/1s9AH2bOQNYcwjpZ2w7bbmdVrfFyPikJF4OINQG4mUKg) for common installation issues with the Steam build. The Steam build is being updated semi-regularly now and I would advise using it over the dev build if you are unable to work out the installation process.
