### ISSUE TITLE
Game Instantly Crashing Upon Loading

### ISSUE THREAD

**Issue by TheOutcastVirus** [swf541/ColdWarIronCurtain#125]
I'm on the Microsoft store version of the game. The game loads fine, with the wallpapers and music, but on reaching 100%, it crashes instantly. I re-installed it twice (manually and using the paradox mods site) but it has the same effect.

**Comment by TheOutcastVirus** [comment]
I've also manually installed the dev build but it has the same problem.

**Comment by DiscordRevolt** [comment]
Closed for being outdated and half Invalid (We dont host the mod outside of Steam and Github)
