### ISSUE TITLE
[Interface] Periodic Maintenance and Predictive maintenance

### ISSUE THREAD

**Issue by Nukola16** [swf541/ColdWarIronCurtain#152]
Referring to the title's research techs in the industry tab.
The game tooltips don't show that they are mutually exclusive. I think that the forking after Preventive Maintenance is not enough to show players that they actually are mutually exclusive.

**Comment by DiscordRevolt** [comment]
Fixed with [23704ad](https://github.com/swf541/ColdWarIronCurtain/commit/23704ada7d41891db8ef6c78722391458e51218d)
