### ISSUE TITLE
Crash possibly related to "Algerian Struggle" focus, or "French Elections"

### ISSUE THREAD

**Issue by CyPher997** [swf541/ColdWarIronCurtain#154]
Playing on a clean install, with all DLC present, and only the workshop build of this mod active, I am getting a crash that may be connected to the "PRC_50s-The_Algerian_Struggle" Focus.

I reproduced this on two seperate saves, both times playing Argentina.
The crash occurs somewhere around December / November 1949, with the last couple lines in the error.log looking like this:
`[21:22:06][effectimplementation.cpp:10730]: common/on_actions/PRC_on_actions.txt:578: complete_national_focus: Unkown focus scripted PRC_50s-The_Algerian_struggle`

The exception.txt file of the crashdump consistently points out an EXCEPTION_ACCESS_VIOLATION

It may be unrelated to the algeria-focus, though, as there are also some lines indicating a missing texture file, specifically the portrait for Georges_Bidault - the french election seems to come up at around that time... maybe that missing texture triggers the exception.

The files:
[error.log](https://github.com/swf541/ColdWarIronCurtain/files/9087060/error.log)
[exception.txt](https://github.com/swf541/ColdWarIronCurtain/files/9087061/exception.txt)

**Comment by CyPher997** [comment]
update: i looked through the files for a bit, and noticed that the portraits are all in .DDS format.
Located the line in the event script for the french election, seems like the portrait for Georges Bidault was the only one referenced with the .TGA extension... changing the reference to the correct filetype seems to resolve the issue at least partially - my second savegame, a few in-game days before the crash normally occured, is handling the elections correctly now, without crashing. The other savegame is still crashing when the event fires... I can live with that though.

Either way, hope you can fix this in the next release!
Great mod, seems like fun so far.

**Comment by swf541** [comment]
Thank you for your report, I will check it out in the coming days.

**Comment by DiscordRevolt** [comment]
Closed; Seems like swf fixed this
