### ISSUE TITLE
Incorrect Things

### ISSUE THREAD

**Issue by SinoSteel** [swf541/ColdWarIronCurtain#159]
The Communist Party of China did not attack to restart the Civil War in 1946. The Guomintang broke the Double Tenth agreement

DPRK did not attack first. The South attacked first, and the subsequent invasion by the North fully ignited the Korean Civil War

The US did not arm the ROK before or after the Korean Civil War, the buildup should be slow until the 80s because of corruption and the military dictatorships. Just like many other fake "democracies", South Korea only became more prosperous around the 80s, and despite taking the brunt of the worst damage, North Korea was arguably more prosperous than the South until the 1970s.

If you add an option for China in focuses to puppet the DPRK which is extremely unlikely in real life, then you should make it so you can only do so if you have 3 million men in the field and at least 2 million inside Korea (in the three years upwards to 3 million volunteers from China fought in Korea and became the frontlines which made Kim Il-sung unhappy)

The Develop the Type 63 Rifle focus incorrectly gives Type 56 rifle bonus not 63

Backyard furnaces makes no sense, should be reworked

If you don't have a Four Pests Campaign event then the Great Leap Forward is more likely to succeed, you should have focuses or decisions that branches out to make the Great Leap Forward succeed. Because the end of that focus tree looked halfassed, I didn't even bother finishing it

If you don't get some of the focuses and get modifiers from it then the next decade's focuses should have bypasses

Don't know why famous Communist generals start off with no traits and lv 1. Some eventually become famous Marshals. So I don't understand why some are not promoted at start.

Why are generals not assignable to give army exp and army bonuses?

No political advisors to choose from?

No ship companies? Really Jiangnan, Dagu, Dalian, and many others ignored. Are there focuses that eventually adds them or something?

The air options are ridiculous and keeps on focusing on ground attack

The political and social law changes have modifiers that makes no sense

If you have 600 million people and your "choices" are "100% of per capita" you should not be getting per month or gdp yearly debt of 600 BILLION upon selection when your gdp isnt even 300 billion or 100 billion monthly...600 million per capita is fucking 600 million per capita not 600 billion per capita... there isn't 600 billion people in China
100% per capita when you have 300 billion gdp and 600 million people means 300 billion divided by 600 million which is 500, one month so times 12 equals 6000 millions hence 6 billion per monthly cost, there's no reason if I select a choice that says "100% of per capita cost" and suddenly my monthly bar incurs a massive 600 billion dollar debt and bankrupts me

Military industry should contribute to gdp, should have modifer bonuses like the others as well as civilian industries

**Comment by DiscordRevolt** [comment]
Closed due to age; PRC Rework in development
