### ISSUE TITLE
Game Crashes on Focus WGR_Expand_the_Ritterstrasse

### ISSUE THREAD

**Issue by Rossebma** [swf541/ColdWarIronCurtain#160]
When I hover over the Focus "WGR_Expand_the_Ritterstrasse" from the Focus-Tree "WGR_60s" my game crashes. I worked around the issue by giving me the focus via editing the save game, but I think you might wanna look into this. As i don't have any idea about the hoi4 crash files, I can't provide them now. But if you explain me how, I will.

//Edit:
It was not the only one. The following Focuses cause crashes while hovering over them:
1. "WGR_Expand_the_Ritterstrasse"
2. "WGR_The_Effelsberg_Radio_Telescope"
3. "WGR_Establish_the_German_Development_Institute"

**Comment by swf541** [comment]
Thank you, fixed the first, will check the other 3 when i got time, I appreciate the report.

**Comment by DiscordRevolt** [comment]
Closed; WGR Received rework
