### ISSUE TITLE
Dosen't Start when Pressing Play

### ISSUE THREAD

**Issue by TheYugoslavGuy** [swf541/ColdWarIronCurtain#171]
So Basiclly i try to Launch the Mod with the Music Mod and some others like more construction building/ Maximum, FPS Map, Player Led PD, rename Faction. enhanced diplo Decisions. recall Volunteers. colourblind mod and create faction decision and it just dosen't even start. The Game runs in the backround but nothing else no loading screen no main menu screen nothing.

**Comment by ricardoffnunes** [comment]
Way too many unsupported mods that we do not activelly endorse and might be conflicting with CW:IC.
