### ISSUE TITLE
T-84N in the korean war

### ISSUE THREAD

**Issue by thehumanbeing1** [swf541/ColdWarIronCurtain#177]
playing as communist china, I sent volunteer divisions to korea, some of them were armored units, and I noticed I have T-84N tanks in some of those units, even though 1. I am not producing them 2. It's 1951 (ironman game)
![image](https://github.com/swf541/ColdWarIronCurtain/assets/138598791/761b9a4d-7e21-4e7d-b4a3-32502327ac36)

**Comment by luke-a-thompson** [comment]
Fixed by @Sealeon
