### ISSUE TITLE
Send Volunteers Bug. (

### ISSUE THREAD

**Issue by GitAtlet** [swf541/ColdWarIronCurtain#180]
From the last update, there is a visual that shows no divisions able to be sent, shows just a empty box
USA, and SOV is affected, Didnt check other countries
(![image](https://github.com/swf541/ColdWarIronCurtain/assets/82807677/f2c214ac-4d87-48a2-8186-7eeef142bf7b))

**Comment by DiscordRevolt** [comment]
Closed; I cant replicate as USA, likely fixed
