### ISSUE TITLE
Consumer good

### ISSUE THREAD

**Issue by JensiePensieFancyKevertje** [swf541/ColdWarIronCurtain#181]
![image](https://github.com/swf541/ColdWarIronCurtain/assets/94914349/aa7656eb-c31e-4e0f-aa27-3ab5e3a65038)

The calculation for the amount of consumer good factories seems to be wrong.

**Comment by ricardoffnunes** [comment]
Fixed on https://github.com/swf541/ColdWarIronCurtain/commit/8077a27670f8f72e1e05aa8ad9542ce71e8d411c
