### ISSUE TITLE
Playing as US...cannot not use host country airports when given military access to fight war along side of them

### ISSUE THREAD

**Issue by stevemtu** [swf541/ColdWarIronCurtain#183]
Playing as US. When fighting along side of Republic of China or Vietnam with military access, I cannot use their airports for US planes.

Obviously I can't 'Join wars' as a Democracy (usually), but from a realism point of view, the US should be able to use its air force in thee conflicts as a 'co-fighter'.

I have enabled
Cold war Iron curtain: a world divided
CWIC Fast Contracts
Cold War Iron Curtain Music

Thanks

**Comment by DiscordRevolt** [comment]
Closed; Hard Coded afaik, You can only get involved with volunteers or directly joining the war
