### ISSUE TITLE
Weapons of Mass Destruction & United Nations - Sticky/Persistent overlays bug

### ISSUE THREAD

**Issue by ricardoffnunes** [swf541/ColdWarIronCurtain#191]
**Problem:**

When accessing either the "Weapons of Mass Destruction" or "United Nations" sections, users encounter a sticky overlay behavior. The issue arises when attempting to close these overlays after opening another native tab, such as "Decisions," "Intelligence Agency," "Research," "Diplomacy," "Trade," "Construction," "Production," "Recruit & Deploy," "Logistics," or "Officer Corps."

**Expected Behavior:**

Ideally, the sticky overlays associated with "Weapons of Mass Destruction" and "United Nations" should seamlessly close when users navigate to other native tabs, ensuring a smooth and intuitive user experience.

**Steps to Reproduce:**

1. Open the "Weapons of Mass Destruction" or "United Nations" section.
2. Navigate to any other native tab mentioned above.
3. Observe that the persistent overlay from the initial section fails to close as anticipated, creating an obstruction to the native tab.

**Additional Information:**

This issue impacts the overall usability and flow of the platform, causing inconvenience for users attempting to switch between different sections efficiently. A resolution to this problem would greatly enhance the user experience and improve the functionality of the mod.

**Comment by ricardoffnunes** [comment]
Working to solve this.

**Comment by ricardoffnunes** [comment]
Regrettably, this issue is deemed unsolvable due to constraints within the engine. The code required to enable the automatic closure of tabs is either inaccessible or not exposed, making a resolution unattainable at this time.

**Comment by luke-a-thompson** [comment]
> Regrettably, this issue is deemed unsolvable due to constraints within the engine. The code required to enable the automatic closure of tabs is either inaccessible or not exposed, making a resolution unattainable at this time.

This is true. Youre welcome to join our team if you're interested in helping in other ways.
Thanks
