### ISSUE TITLE
Wrong State Target in 50s_ZIM.txt

### ISSUE THREAD

**Issue by Sealeon** [swf541/ColdWarIronCurtain#24]
The focus ZIM_Kariba_Dam_Project in 50s_ZIM.txt targets state 986: "Chimbu" in Papua New Guinea instead of either state 246: "Choma" in Zambia or state 1273: "Mashonaland West" in Zimbabwe where the dam is located

**Comment by Harain** [comment]
changed to state 1446, where Kariba actually is, many states bordering the place, seemed the best for me
