### ISSUE TITLE
Missing state target in NGA_1950_dawn_of_nigerian_industry

### ISSUE THREAD

**Issue by hfadmin** [swf541/ColdWarIronCurtain#34]
In common/national_focus/50s_NGA.txt the focus NGA_1950_dawn_of_nigerian_industry is lacking a state target.

**Comment by KRaw21** [comment]
The NGA tree is WIP right now, so it should be resolved soon.

**Comment by herrcaptain** [comment]
No worries! Just trying to help out in what little ways I can by pointing out issues. I also noticed the same issue with NGA_1950_rehabilitate_coastal_defenses (lacking a state target). Thanks for the hard work on this excellent mod!

**Comment by AssassinVaughan** [comment]
Currently waiting on new map work before I assign these things to states, its a temporary WIP thing

**Comment by herrcaptain** [comment]
Thanks for the heads up! Once again, great work!

**Comment by Harain** [comment]
seems to have been fixed at some point
