### ISSUE TITLE
Game crash when i send volunteers

### ISSUE THREAD

**Issue by Shearba** [swf541/ColdWarIronCurtain#38]
Every time I send volunteers as the U.S.A to the republic of china my game crashes on June 7th 1949. Im really disappointed because this mod looks so fun.

**Comment by Shearba** [comment]
I decided not to send volunteers to china, unfortunately during the korean war my game continues to crash around august 1950. Right when I was about to defeat north korea I got a notification that communist china would get involved if I continued to take over korea. As soon as I continue my game would crash. I believe every time I get in some kind with communist china my game crashes which is really dissapointing.

**Comment by Harain** [comment]
this is too old to reproduce, doesn't seem to happen
