### ISSUE TITLE
Unrelated Events on ENG First Day

### ISSUE THREAD

**Issue by Sealeon** [swf541/ColdWarIronCurtain#46]
After 1 day has ticked for ENG (24/5/1949) 2 events fire that are for other countries.  
One is the event sov.102 in the event file SovietUnion.txt which needs to simply be scoped to SOV.  
The other is india.3 from the event file India.txt which requires "is_triggered_only = yes" to avoid accidental firing.

**Comment by Harain** [comment]
fixed, thx for reporting
