### ISSUE TITLE
Missing Focuses

### ISSUE THREAD

**Issue by Harain** [swf541/ColdWarIronCurtain#52]
list of all I found in error logs from players

`events/Niger.txt:28: complete_national_focus: Unkown focus scripted NIG_Sawaba_Coup_Attempt`
`events/Niger.txt:28: complete_national_focus: Unkown focus scripted NIG_Coup_Failure`
`events/Niger.txt:29: complete_national_focus: Unkown focus scripted NIG_Sawaba_Takeover`
`events/Morocco.txt:1449: complete_national_focus: Unkown focus scripted MOR_60s_PRES_ELECTION_1968`

going through vsc errors also found the following:

`common\national_focus\60s_ZIM.txt: ZIM_60s_african_nationalism`
`common\scripted_effects\IC_scripted_effects.txt: NGA_1960s_Biafran_War`
`events\Britain.txt: ENG_Election_of_1950`
`events\Cambodia.txt: CAM_Royalist_Partisan_Faction, CAM_Viet_Minh_Backed_Faction`
`events\Cuba.txt: complete_national_focus = CUB_1952_elections, CUB_roberto_agramonte, CUB_hevia`
`events\EastGerman_1960s.txt: complete_national_focus = DDR_60s_DDR_60s_First_Secretary_Honecker`
`events\EastGermany.txt: complete_national_focus = DDR_The_Kingdom_of_Prussia, DDR_Democratic_Reunification, DDR_Radicalization_of_the_NDPD, DDR_Leave_the_Warsaw_Pact`
`events\French_Elections.txt: complete_national_focus = FRA_60s_Censor_Motion_Rejected`
`events\Ghana_Events.txt: complete_national_focus = GHA_Election_of_1956`
`events\Greece.txt: complete_national_focus = GRE_Officers_Coup_Attempt_1951, GRE_Papagos_Intervenes`
`events\Iraq.txt: complete_national_focus = IRQ_Constitutional_Union_Victory, IRQ_United_Popular_Front, IRQ_Istiqlal_Victory`
`events\kenya2.txt: complete_national_focus = KEN_60s_the_third_way`
`events\Morocco.txt: complete_national_focus = MOR_50s_FRANCE_ACCEPT, MOR_50s_FRANCE_REJECT, MOR_60s_PRES_DAH_BARKA, MOR_60s_PRES_ELECTION_1968, MOR_60s_REP_PRES_DAH_BARKA_68`
`events\Niger.txt: NIG_Military_Coup_Attempt, NIG_Crush_the_Military_Coup, NIG_Successful_Coup`
`events\North Vietnam.txt: complete_national_focus = VIN_A_Unified_Vietnam, VIN_The_Unification_War, VIN_Accept_the_Division`
`events\Persia.txt: complete_national_focus = PER_Republic_of_Iran, PER_Failure_of_the_Revolution`
`events\saf.txt: complete_national_focus = SAF_60s_Election_of_1961, SAF_60s_nasionale_party, SAF_60s_United_Party, SAF_60s_Progressive_Victory, SAF_60s_1966_Elections, SAF_60s_nasionale_party_66, SAF_60s_United_Party_66, SAF_60s_Progressive_Victory_1966, SAF_60s_1970_Election, SAF_60s_nasionale_party_70, SAF_60s_United_Victory_70, SAF_60s_Progressive_Victory_1966`
`events\SovietUnion.txt: complete_national_focus = KPA_Comrade_Ho_Ka_I`
`events\Suez_Crisis.txt: complete_national_focus = USA_Suez_Crisis`
`events\Turkey.txt: complete_national_focus = TUR_Failure_of_coup, TUR_New_Turkey`

most of these are probably leftovers from old removed trees, but some of these events are still getting called

**Comment by swf541** [comment]
Fixed
