### ISSUE TITLE
Soviet Idea

### ISSUE THREAD

**Issue by Harain** [swf541/ColdWarIronCurtain#56]
Atm, SOV start with the Idea Soviet_Labor_Shortage "Labor Shortages Issues"

the event every1.2 adds the idea sov_labor_short "Significant Labor Shortages"

this can later be reduced by a focus to sov_labor_short_1 "Labor Shortages"

which can then be removed by another focus

problem is that the original Soviet_Labor_Shortage remains, confusing the players because of the almost identical names

a solution would be an early way to remove Soviet_Labor_Shortage, because the others come much later on

**Comment by swf541** [comment]
Adapted the later content to modify the older idea since its all referring to the same fundamental issues
