### ISSUE TITLE
Khrushchev tree issue

### ISSUE THREAD

**Issue by Harain** [swf541/ColdWarIronCurtain#71]
https://discordapp.com/channels/459126880998522882/470328480924434434/813813260498763798

from @StarChaser010 in #bug-reports
...
Also there is logic issue with this focus.  Renaming cities happened after 20 CPSU congress (February 1956) and official proclamation  policy of destalinization, and the event in this focus ("the restoration of public order") references suppression of march 1956 riots in Tbilisi, Georgia, whose triggering referenced in event "the tbilisi riot" in another focus, much lower down that tree line (Remove monuments to Stalin).

Maybe rearrange focuses in this tree like that in my picture, because "doctor affair" was closed and people charged was rehabilitated in 1954, way before 20 CSPU congress.

So, maybe swap "Reveal fallacious doctor plot" and "restore public order", make the latter to be dependent on "remove the monuments to Stalin"
![image](https://user-images.githubusercontent.com/6484567/108885259-7d0c4b00-75ff-11eb-9936-91d7804d4dba.png)

**Comment by DiscordRevolt** [comment]
Closed due to tree having been reworked
