### ISSUE TITLE
Wrong focus icon

### ISSUE THREAD

**Issue by Harain** [swf541/ColdWarIronCurtain#75]
https://discordapp.com/channels/459126880998522882/470328480924434434/814131830437052425

"Modernize gas facilities" focus icon are misleading. There are people with gas masks and NBC suits, implying it is about poison gas, while description are about gasoline and more gas stations.

Maybe replace it with some generic fuel-related icon?

![image](https://user-images.githubusercontent.com/6484567/109010744-12fbb080-76a8-11eb-8286-1ec9681f1882.png)

**Comment by swf541** [comment]
swapped the icon
