### ISSUE TITLE
PHI 50s tree issues

### ISSUE THREAD

**Issue by Harain** [swf541/ColdWarIronCurtain#87]
3 focuses in PHI_1950s.txt (PHI_End_the_Huk_Insurgency, PHI_Crush_the_Huks and PHI_An_End_to_the_Huk_Insurgency) check for hukbalahap_seccessionism country flag which isn't set anywhere, making all 3 focuses always bypass instantly

**Comment by swf541** [comment]
Interesting

**Comment by swf541** [comment]
Fixed had the wrong flag being checked
