### ISSUE TITLE
French Indochina issue

### ISSUE THREAD

**Issue by Harain** [swf541/ColdWarIronCurtain#88]
https://discordapp.com/channels/459126880998522882/470328480924434434/817117030939230229

"Don't know if it's the good place for this, but as USA, I have chosen the ''help France militarily'' in Vietnam. In 1951 we crushed the Viet minh within a month. However, in June 1954, I still have the Geneva accord, and a communist north vietnam is created...wich is a nonsense due to the victory of France/USA against the Viet minh. I specify that France agreed to decolonized and I backed Diem but nothing happened before the 1954 event."

**Comment by swf541** [comment]
Should be fixed, added new failsafes to the missions
