### ISSUE TITLE
US Edicts issue

### ISSUE THREAD

**Issue by Harain** [swf541/ColdWarIronCurtain#89]
from https://discordapp.com/channels/459126880998522882/470328480924434434/817208983273209856

"Every idea that President MacArthur gets for his 1952 focus tree,  for example Compulsory Work for the Unemployed, Military Youth Program, and Veteran Affairs and War Relief instantly are removed the moment the focus adds them"

Only checked the 1st:
edict_welfare_program_compulsorywork (added by USA_MACARTHUR_Restore_the_Civil_Conservation_Corps) has available = { always = no } since the has_country_flag is commented

could that be it @swf541 ?

**Comment by swf541** [comment]
Should be fixed
