### ISSUE TITLE
Game CTD at start

### ISSUE THREAD

**Issue by aurreko** [swf541/ColdWarIronCurtain#93]
First sorry my english and thanks for your mod.When i try to play with your mod installed my game ctd at the end of loading mod screenshots(it's written "precalculated naval distances"such as in vanilla game).The error log says:"['hour']**[effectimplementation.cpp:19429]: : invalid on_win event for start border war**" and "['hour']**[effectimplementation.cpp:19442]: : invalid on_lose event for start border war**".I have:1)**all DLCs**-2)**no other mods installed**-3)**HOI version 1.10.2**-4)**Paradox Launcher version 2020.11**-5)**CWIC 06/03 version**.I tried also with the previous version but it's the same.Hi and thanks for any reply

**Comment by Harain** [comment]
this is a known issue that happens with PCs with a weak graphics card

you can try the steps described in the following document, it helps in many cases, but not all

https://docs.google.com/document/d/1s9AH2bOQNYcwjpZ2w7bbmdVrfFyPikJF4OINQG4mUKg/edit?usp=sharing

**Comment by aurreko** [comment]
Many thanks for the quick reply,i'll try your tip.

Il giorno dom 7 mar 2021 alle ore 20:51 Harain <notifications@github.com>
ha scritto:

**Comment by aurreko** [comment]
It works,i switched from integrated to dedicated videocard and it's all
ok!many thanks for all,man

Il giorno dom 7 mar 2021 alle ore 21:01 chi losa <
chilosachiequesto@gmail.com> ha scritto:
